language: cpp

branches:
  only:
    - master

dist: bionic

addons:
  apt:
    packages:
    - cmake
    - make
    - g++
    - pkg-config

python:
  - "3.7"

# Install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++ make python3-pip

install:
  - pip3 install --user websocket-client

# Build steps
script:
  - ./run_ci.sh

notifications:
  email:
    - mrseakg@gmail.com